import { Place } from "./models";

export const demoPlaces: Place[] = [
  {
    id: "tartine",
    name: "Tartine Bakery",
    address: "600 Guerrero St, San Francisco, CA",
    latitude: 37.7614,
    longitude: -122.4241,
    category: "cafe",
    status: "wantToGo",
    sourcePlatform: "instagram",
    priceRange: "$$",
    note: "Morning bun first.",
    time: "9:00 AM",
  },
  {
    id: "ramen-nagi",
    name: "Ramen Nagi",
    address: "541 Valencia St, San Francisco, CA",
    latitude: 37.7642,
    longitude: -122.4214,
    category: "food",
    status: "visited",
    sourcePlatform: "threads",
    priceRange: "$$",
    note: "Black King ramen.",
    time: "12:30 PM",
  },
  {
    id: "the-interval",
    name: "The Interval",
    address: "2 Marina Blvd, San Francisco, CA",
    latitude: 37.8064,
    longitude: -122.409,
    category: "bar",
    status: "wantToGo",
    sourcePlatform: "other",
    priceRange: "$$$",
    note: "Great sunset stop.",
    time: "6:30 PM",
  },
  {
    id: "palace-of-fine-arts",
    name: "Palace of Fine Arts",
    address: "3601 Lyon St, San Francisco, CA",
    latitude: 37.8021,
    longitude: -122.4488,
    category: "attraction",
    status: "wantToGo",
    sourcePlatform: "googleMaps",
    note: "Good for golden hour.",
    time: "5:00 PM",
  },
];
